name: localization
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.5
  - matplotlib
  - numpy
  - pyyaml
  - opencv
  - tensorflow-gpu
  - pytorch==1.4.0
  - keras
  - scikit-learn
  - scikit-image
  - pandas
  - utm
  - tqdm